{{- include "ffc-helm-library.container-config-map" (list . "ffc-elm-plan-service.config-map") -}}
{{- define "ffc-elm-plan-service.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PLAN_EVENT_QUEUE_CREATE: {{ quote .Values.queues.planEventQueue.create }}
  PLAN_EVENT_QUEUE_NAME: {{ quote .Values.queues.planEventQueue.name }}
  PLAN_EVENT_QUEUE_ENDPOINT: {{ quote .Values.queues.planEventQueue.endpoint }}
  PLAN_EVENT_QUEUE_URL: {{ quote .Values.queues.planEventQueue.url }}
  PLAN_EVENT_QUEUE_REGION: {{ quote .Values.queues.planEventQueue.region }}
  PORT: {{ quote .Values.container.port }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUsername }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDatabase }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
{{- end -}}
